_wandb:
    value:
        cli_version: 0.25.0
        e:
            091moy6infgkpmamxxy2x7ujxesm6kf4:
                codePath: wandb_test.py
                codePathLocal: wandb_test.py
                email: canchen981@gmail.com
                executable: /root/autodl-tmp/conda/envs/HEIST/bin/python
                host: autodl-container-31eb41bf76-7aeec792
                os: Linux-5.15.0-94-generic-x86_64-with-glibc2.35
                program: /root/autodl-tmp/HEIST/wandb_test.py
                python: CPython 3.10.19
                root: /root/autodl-tmp/HEIST
                startedAt: "2026-03-05T07:12:47.696058Z"
                writerId: 091moy6infgkpmamxxy2x7ujxesm6kf4
        m: []
        python_version: 3.10.19
        t:
            "3":
                - 2
                - 16
            "4": 3.10.19
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
